[Service]
TimeoutStartSec=180s
ExecStartPre=/usr/bin/python3 /opt/vprouter/current/host/collector_services.py stop
ExecStartPost=/usr/bin/python3 /opt/vprouter/current/host/collector_services.py start
ExecStopPost=/usr/bin/python3 /opt/vprouter/current/host/collector_services.py stop
